AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance

Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      # Add more instance types as needed

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-03f65b8614a860c29  # Replace this with the desired AMI ID for your region
      # Replace ami-xxxxxxxxxxxxxxxxx with the appropriate AMI ID for your region.
      # You can find AMI IDs in the AWS Management Console or using AWS CLI/SDK.

Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Description: ID of the created EC2 instance
  PublicDnsName:
    Value: !GetAtt EC2Instance.PublicDnsName
    Description: Public DNS name of the created EC2 instance
